name: easycount
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.2.1
  intl: ^0.17.0
  intl_phone_field: ^3.2.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  webview_flutter: ^4.0.1
  pdf: ^3.11.1
  printing: ^5.9.0
  excel: ^2.0.3


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
